export type WatchEntry = {
  name: string;
  aliases?: string[];
  type: "individual" | "company";
  lists: string[];
  country?: string;
  reason: string;
  risk: "high" | "medium";
};

/** Publicly reported watchlist / PEP names for the demo engine — not a production feed. */
export const WATCHLIST: WatchEntry[] = [
  {
    name: "Kim Jong Un",
    aliases: ["Kim Jong-un", "Kim Jongun"],
    type: "individual",
    lists: ["OFAC", "UN SECURITY COUNCIL", "EU CONSOLIDATED"],
    country: "KP",
    reason: "DPRK leadership — designated on multiple sanctions programmes.",
    risk: "high",
  },
  {
    name: "Yevgeniy Viktorovich Prigozhin",
    aliases: ["Yevgeny Prigozhin", "Evgeny Prigozhin", "Prigozhin"],
    type: "individual",
    lists: ["OFAC", "EU CONSOLIDATED", "HM TREASURY"],
    country: "RU",
    reason: "Wagner Group founder — Russia-related sanctions designations.",
    risk: "high",
  },
  {
    name: "Wagner Group",
    aliases: ["PMC Wagner", "ChVK Wagner", "Wagner PMC"],
    type: "company",
    lists: ["OFAC", "EU CONSOLIDATED", "HM TREASURY"],
    country: "RU",
    reason: "Designated private military company on Russia-related programmes.",
    risk: "high",
  },
  {
    name: "Sinaloa Cartel",
    aliases: ["Cartel de Sinaloa", "CDS"],
    type: "company",
    lists: ["OFAC", "INTERPOL"],
    country: "MX",
    reason: "Foreign terrorist organization / narcotics trafficking designation.",
    risk: "high",
  },
  {
    name: "Islamic Revolutionary Guard Corps",
    aliases: ["IRGC", "Sepah", "Pasdaran"],
    type: "company",
    lists: ["OFAC", "EU CONSOLIDATED", "HM TREASURY"],
    country: "IR",
    reason: "Iranian military organisation designated on terrorism programmes.",
    risk: "high",
  },
  {
    name: "Bank Sepah",
    aliases: ["Bank Sepah Iran"],
    type: "company",
    lists: ["OFAC", "UN SECURITY COUNCIL", "EU CONSOLIDATED"],
    country: "IR",
    reason: "Iranian state bank designated for WMD proliferation financing.",
    risk: "high",
  },
  {
    name: "Rosoboronexport",
    aliases: ["JSC Rosoboronexport", "ROE"],
    type: "company",
    lists: ["OFAC", "EU CONSOLIDATED"],
    country: "RU",
    reason: "Russian state arms exporter on sectoral / defence sanctions lists.",
    risk: "high",
  },
  {
    name: "Al-Qaeda",
    aliases: ["Al Qaeda", "Al-Qaida", "AQ"],
    type: "company",
    lists: ["OFAC", "UN SECURITY COUNCIL", "EU CONSOLIDATED", "HM TREASURY"],
    reason: "UN-listed terrorist organisation.",
    risk: "high",
  },
  {
    name: "Hamas",
    aliases: ["Harakat al-Muqawama al-Islamiya", "Islamic Resistance Movement"],
    type: "company",
    lists: ["OFAC", "EU CONSOLIDATED", "HM TREASURY"],
    reason: "Designated terrorist organisation.",
    risk: "high",
  },
  {
    name: "Hezbollah",
    aliases: ["Hizballah", "Hizbollah"],
    type: "company",
    lists: ["OFAC", "EU CONSOLIDATED", "HM TREASURY"],
    reason: "Designated terrorist organisation.",
    risk: "high",
  },
  {
    name: "Taliban",
    aliases: ["Islamic Emirate of Afghanistan"],
    type: "company",
    lists: ["UN SECURITY COUNCIL", "OFAC", "EU CONSOLIDATED"],
    country: "AF",
    reason: "UN 1988 / Taliban sanctions programme.",
    risk: "high",
  },
  {
    name: "ISIS",
    aliases: ["ISIL", "Islamic State", "Daesh", "Islamic State of Iraq and Syria"],
    type: "company",
    lists: ["OFAC", "UN SECURITY COUNCIL", "EU CONSOLIDATED", "HM TREASURY"],
    reason: "UN-listed terrorist organisation.",
    risk: "high",
  },
  {
    name: "Joaquin Guzman Loera",
    aliases: ["El Chapo", "Joaquín Guzmán", "Chapo Guzman"],
    type: "individual",
    lists: ["OFAC", "INTERPOL"],
    country: "MX",
    reason: "Sinaloa Cartel leadership — narcotics kingpin designation.",
    risk: "high",
  },
  {
    name: "Viktor Yanukovych",
    aliases: ["Viktor Yanukovich"],
    type: "individual",
    lists: ["EU CONSOLIDATED", "HM TREASURY", "PEP DATABASE"],
    country: "UA",
    reason: "Former head of state with EU misappropriation designations; PEP.",
    risk: "high",
  },
  {
    name: "Bashar al-Assad",
    aliases: ["Bashar Assad", "Bashar Hafez al-Assad"],
    type: "individual",
    lists: ["OFAC", "EU CONSOLIDATED", "HM TREASURY", "PEP DATABASE"],
    country: "SY",
    reason: "Syrian head of state — Syria sanctions programmes.",
    risk: "high",
  },
  {
    name: "Nicolás Maduro",
    aliases: ["Nicolas Maduro", "Nicolas Maduro Moros"],
    type: "individual",
    lists: ["OFAC", "EU CONSOLIDATED", "PEP DATABASE"],
    country: "VE",
    reason: "Venezuelan head of state — Venezuela-related designations; PEP.",
    risk: "high",
  },
  {
    name: "Alexander Lukashenko",
    aliases: ["Aleksandr Lukashenko", "Alyaksandr Lukashenka"],
    type: "individual",
    lists: ["OFAC", "EU CONSOLIDATED", "HM TREASURY", "PEP DATABASE"],
    country: "BY",
    reason: "Belarusian head of state — Belarus sanctions programmes; PEP.",
    risk: "high",
  },
  {
    name: "Internet Research Agency",
    aliases: ["IRA", "Glavset"],
    type: "company",
    lists: ["OFAC", "EU CONSOLIDATED"],
    country: "RU",
    reason: "Russian influence operation designated for election interference.",
    risk: "high",
  },
  {
    name: "Bank of Kunlun",
    aliases: ["Kunlun Bank"],
    type: "company",
    lists: ["OFAC"],
    country: "CN",
    reason: "Designated for facilitating Iranian financial activity.",
    risk: "high",
  },
  {
    name: "Emmanuel Macron",
    aliases: ["President Macron"],
    type: "individual",
    lists: ["PEP DATABASE"],
    country: "FR",
    reason: "Current head of state — politically exposed person, not sanctioned.",
    risk: "medium",
  },
  {
    name: "Joe Biden",
    aliases: ["Joseph Biden", "Joseph R. Biden"],
    type: "individual",
    lists: ["PEP DATABASE"],
    country: "US",
    reason: "Current / recent head of state — politically exposed person.",
    risk: "medium",
  },
  {
    name: "Keir Starmer",
    type: "individual",
    lists: ["PEP DATABASE"],
    country: "GB",
    reason: "Current head of government — politically exposed person.",
    risk: "medium",
  },
  {
    name: "Olaf Scholz",
    type: "individual",
    lists: ["PEP DATABASE"],
    country: "DE",
    reason: "Recent head of government — politically exposed person.",
    risk: "medium",
  },
  {
    name: "Narendra Modi",
    type: "individual",
    lists: ["PEP DATABASE"],
    country: "IN",
    reason: "Current head of government — politically exposed person.",
    risk: "medium",
  },
  {
    name: "World-Check Demo Entity",
    aliases: ["World Check Demo"],
    type: "company",
    lists: ["ADVERSE MEDIA", "WORLD-CHECK"],
    reason: "Adverse media hit used for engine demonstration.",
    risk: "medium",
  },
];
